package jp.ne.ruru.park.ando.protoviewer.tree;


/* Generated By:JJTree&JavaCC: Do not edit this line. ProtoParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ProtoParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int CSTRING_TKN = 6;
  /** RegularExpression Id. */
  int EQUL_TKN = 7;
  /** RegularExpression Id. */
  int SEMI_COLON_TKN = 8;
  /** RegularExpression Id. */
  int COLON_TKN = 9;
  /** RegularExpression Id. */
  int CONNMA_TKN = 10;
  /** RegularExpression Id. */
  int DOT_TKN = 11;
  /** RegularExpression Id. */
  int TO_TKN = 12;
  /** RegularExpression Id. */
  int LEFTBRACE_TKN = 13;
  /** RegularExpression Id. */
  int RIGHTBRACE_TKN = 14;
  /** RegularExpression Id. */
  int LEFTPAREN_TKN = 15;
  /** RegularExpression Id. */
  int RIGHTPAREN_TKN = 16;
  /** RegularExpression Id. */
  int LEFTBRACKET_TKN = 17;
  /** RegularExpression Id. */
  int RIGHTBRACKET_TKN = 18;
  /** RegularExpression Id. */
  int LESSTHAN_TKN = 19;
  /** RegularExpression Id. */
  int GRATETHAN_TKN = 20;
  /** RegularExpression Id. */
  int SYNTAX_TKN = 21;
  /** RegularExpression Id. */
  int BOOLEAN_TKN = 22;
  /** RegularExpression Id. */
  int ATTRIBUTE_TKN = 23;
  /** RegularExpression Id. */
  int OPTION_TKN = 24;
  /** RegularExpression Id. */
  int IMPORT_TKN = 25;
  /** RegularExpression Id. */
  int PUBLIC_TKN = 26;
  /** RegularExpression Id. */
  int PACKAGE_TKN = 27;
  /** RegularExpression Id. */
  int SERVICE_TKN = 28;
  /** RegularExpression Id. */
  int MESSAGE_TKN = 29;
  /** RegularExpression Id. */
  int ENUM_TKN = 30;
  /** RegularExpression Id. */
  int ONEOF_TKN = 31;
  /** RegularExpression Id. */
  int GROUP_TKN = 32;
  /** RegularExpression Id. */
  int EXTENTIONS_TKN = 33;
  /** RegularExpression Id. */
  int EXTEND_TKN = 34;
  /** RegularExpression Id. */
  int MAP_TKN = 35;
  /** RegularExpression Id. */
  int RESERVED_TKN = 36;
  /** RegularExpression Id. */
  int REPEATED_TKN = 37;
  /** RegularExpression Id. */
  int RETURNS_TKN = 38;
  /** RegularExpression Id. */
  int STREAM_TKN = 39;
  /** RegularExpression Id. */
  int TYPE_TKN = 40;
  /** RegularExpression Id. */
  int RPC_TKN = 41;
  /** RegularExpression Id. */
  int NUMBER_TKN = 42;
  /** RegularExpression Id. */
  int DOUBLE_TKN = 43;
  /** RegularExpression Id. */
  int IDENT_TKN = 44;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<SINGLE_LINE_COMMENT>",
    "<CSTRING_TKN>",
    "\"=\"",
    "\";\"",
    "\":\"",
    "\",\"",
    "\".\"",
    "\"to\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"<\"",
    "\">\"",
    "\"syntax\"",
    "<BOOLEAN_TKN>",
    "<ATTRIBUTE_TKN>",
    "\"option\"",
    "\"import\"",
    "\"public\"",
    "\"package\"",
    "\"service\"",
    "\"message\"",
    "\"enum\"",
    "\"oneof\"",
    "\"group\"",
    "\"extensions\"",
    "\"extend\"",
    "\"map\"",
    "\"reserved\"",
    "\"repeated\"",
    "\"returns\"",
    "\"stream\"",
    "<TYPE_TKN>",
    "\"rpc\"",
    "<NUMBER_TKN>",
    "<DOUBLE_TKN>",
    "<IDENT_TKN>",
  };

}
