package jp.ne.ruru.park.ando.protoviewer.tree;


/* Generated By:JavaCC: Do not edit this line. ProtoParserTreeConstants.java Version 6.1_2 */
public interface ProtoParserTreeConstants
{
  public int JJTINPUT = 0;
  public int JJTIMPORTPART = 1;
  public int JJTPUBLICPART = 2;
  public int JJTVALUEPART = 3;
  public int JJTBOOLEANPART = 4;
  public int JJTCSTRINGPART = 5;
  public int JJTNUMBERPART = 6;
  public int JJTDOUBLEPART = 7;
  public int JJTINDENTPART = 8;
  public int JJTBRACEVALUEPART = 9;
  public int JJTBRACEVALUEONEPART = 10;
  public int JJTBRACEVALUEONEBRACKETPART = 11;
  public int JJTSYNTAXPART = 12;
  public int JJTOPTIONPART = 13;
  public int JJTCLASSPART = 14;
  public int JJTCUSTOMOPTIONSPART = 15;
  public int JJTKEYPART = 16;
  public int JJTPACKAGEPART = 17;
  public int JJTSERVICEPART = 18;
  public int JJTRPCPART = 19;
  public int JJTSTREAMPART = 20;
  public int JJTRPCBRACEPART = 21;
  public int JJTMESSAGEPART = 22;
  public int JJTMESSAGEBRANCHEPART = 23;
  public int JJTATTRIBUTEMEMBERPART = 24;
  public int JJTMEMBERPART = 25;
  public int JJTATTRIBUTEPART = 26;
  public int JJTREPEATEDPART = 27;
  public int JJTGROUPPART = 28;
  public int JJTCLASSORTYPEPART = 29;
  public int JJTTYPEPART = 30;
  public int JJTBRACKETPART = 31;
  public int JJTBRACKETMEMBERPART = 32;
  public int JJTENUMPART = 33;
  public int JJTENUMMEMBERPART = 34;
  public int JJTENUMOPTIONMEMBERPART = 35;
  public int JJTRESERVEDPART = 36;
  public int JJTDEVIDERPART = 37;
  public int JJTONEOFPART = 38;
  public int JJTMAPPART = 39;
  public int JJTEXTENTIONSPART = 40;
  public int JJTEXTENDPART = 41;


  public String[] jjtNodeName = {
    "Input",
    "ImportPart",
    "PublicPart",
    "ValuePart",
    "BooleanPart",
    "CStringPart",
    "NumberPart",
    "DoublePart",
    "IndentPart",
    "BraceValuePart",
    "BraceValueOnePart",
    "BraceValueOneBracketPart",
    "SyntaxPart",
    "OptionPart",
    "ClassPart",
    "CustomOptionsPart",
    "KeyPart",
    "PackagePart",
    "ServicePart",
    "RpcPart",
    "StreamPart",
    "RpcBracePart",
    "MessagePart",
    "MessageBranchePart",
    "AttributeMemberPart",
    "MemberPart",
    "AttributePart",
    "RepeatedPart",
    "GroupPart",
    "ClassOrTypePart",
    "TypePart",
    "BracketPart",
    "BracketMemberPart",
    "EnumPart",
    "EnumMemberPart",
    "EnumOptionMemberPart",
    "ReservedPart",
    "DeviderPart",
    "OneOfPart",
    "MapPart",
    "ExtentionsPart",
    "ExtendPart",
  };
}
/* JavaCC - OriginalChecksum=a42d714d733d26ae10b4501e85c8e1b5 (do not edit this line) */
