package jp.ne.ruru.park.ando.protoviewer.tree;


/* Generated By:JavaCC: Do not edit this line. ProtoParserDefaultVisitor.java Version 6.1_2 */
public class ProtoParserDefaultVisitor implements ProtoParserVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTInput node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTImportPart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTPublicPart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTValuePart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTBooleanPart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCStringPart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTNumberPart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTDoublePart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIndentPart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTBraceValuePart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTBraceValueOnePart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTBraceValueOneBracketPart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTSyntaxPart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTOptionPart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTClassPart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCustomOptionsPart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTKeyPart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTPackagePart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTServicePart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTRpcPart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStreamPart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTRpcBracePart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMessagePart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMessageBranchePart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAttributeMemberPart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMemberPart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAttributePart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTRepeatedPart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTGroupPart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTClassOrTypePart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTTypePart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTBracketPart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTBracketMemberPart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTEnumPart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTEnumMemberPart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTEnumOptionMemberPart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTReservedPart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTDeviderPart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTOneOfPart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMapPart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExtentionsPart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExtendPart node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=516719df64bc87f48405e58d93a2ffee (do not edit this line) */
